### ISSUE TITLE
neuester Callhistory Eintrag Vorwählen

### ISSUE THREAD

**Issue by LeeO86** [AWAH-SIP/AWAH-SIP_Desktop-GUI#5]
In GitLab by @andyweiss on Apr 11, 2021, 09:34

Im Feld zur Nummernwahl direkt immer den neuesten Callhistory Eintrag einfüllen. So kann man mit Ender direkt einen ReDial machen

**Comment by LeeO86** [comment]
In GitLab by @andyweiss on Apr 11, 2021, 09:48

changed the description

**Comment by LeeO86** [comment]
In GitLab by @andyweiss on Apr 11, 2021, 09:49

moved from awah-sip_codec#26

**Comment by andyweiss** [comment]
done
